#!/bin/bash

cp ./.dir_colors /home/merijn/

sudo pacman -S xorg-server xorg-xinit compton i3-gaps i3status
cp ./.xinitrc /home/merijn/
cp ./.bashrc /home/merijn/

cp -r ./.config /home/merijn/

sudo pacman -S alsa-utils volumeicon network-manager-applet xfce4-power-manager pulseaudio-git dunst nitrogen xautolock openssh polkit-gnome xarchiver tar unrar unzip p7zip xterm firefox dmenu pcmanfm lxappearance adapta-gtk-theme ttf-ubuntu-font-family ttf-font-awesome

